"""initial migration

Revision ID: 49839b1c0e88
Revises: 
Create Date: 2024-03-31 17:40:22.817613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49839b1c0e88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'stores', ['store_id'], ['_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('store_id')

    # ### end Alembic commands ###
